title: Учимся создавать сайт с GitHub Pages!
author: batsaw
email: btsw.wp@yandex.ru
description: > # this means to ignore newlines until "baseurl:"
  Моя первый сайт созданный с помощью GitHub Pages.
# social links
github_username:  batsaw # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
